<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "anythingslider"
 *
 * Auto generated by Extension Builder 2015-05-02
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
	'title' => 'anything slider',
	'description' => 'anything slider',
	'category' => 'plugin',
	'author' => 'Xiaoling Peng',
	'author_email' => 'pengmaradi@gmail.com',
	'state' => 'stable',
	'internal' => '',
	'uploadfolder' => '1',
	'createDirs' => '',
	'clearCacheOnLoad' => 0,
	'version' => '0.0.3',
	'constraints' => array(
		'depends' => array(
			'typo3' => '6.2',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);